"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#7dc4e4)\
$os\
$username\
[](bg:#8bd5ca fg:#7dc4e4)\
$directory\
[](fg:#8bd5ca bg:#a6da95)\
$git_branch\
$git_status\
[](fg:#a6da95 bg:#eed49f)\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
[](fg:#eed49f bg:#f5a97f)\
$docker_context\
$conda\
$golang\
[](fg:#f5a97f bg:#ee99a0)\
$c\
$rust\
[ ](fg:#ee99a0)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#1e2030'
color_bg1 = '#494d64'
color_bg3 = '#5b6078'
color_blue = '#8aadf4'
color_aqua = '#8bd5ca'
color_green = '#a6da95'
color_orange = '#f5a97f'
color_purple = '#c6a0f6'
color_red = '#ed8796'
color_yellow = '#eed49f'

[os]
disabled = false
style = "bg:#7dc4e4 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#7dc4e4 fg:color_fg0"
style_root = "bg:#7dc4e4 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:#8bd5ca"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#a6da95"
format = '[[ $symbol $branch ](fg:color_fg0 bg:#a6da95)]($style)'

[git_status]
style = "bg:#a6da95"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:#a6da95)]($style)'

[nodejs]
symbol = ""
style = "bg:#eed49f" 
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[c]
symbol = " "
style = "bg:#ee99a0"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#ee99a0)]($style)'

[rust]
symbol = ""
style = "bg:#ee99a0"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#ee99a0)]($style)'

[golang]
symbol = ""
style = "bg:#f5a97f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#f5a97f)]($style)'

[php]
symbol = ""
style = "bg:#eed49f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[java]
symbol = " "
style = "bg:#eed49f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[kotlin]
symbol = ""
style = "bg:#eed49f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[haskell]
symbol = ""
style = "bg:#eed49f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[python]
symbol = ""
style = "bg:#eed49f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[lua]
symbol = ""
style = "bg:#eed49f"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#eed49f)]($style)'

[docker_context]
symbol = ""
style = "bg:#f5a97f"
format = '[[ $symbol( $context) ](fg:#83a598 bg:#f5a97f)]($style)'

[conda]
style = "bg:#f5a97f"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:#f5a97f)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#ee99a0"
format = '[[  $time ](fg:color_fg0 bg:#ee99a0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
